### ISSUE TITLE
No documentation for CodeLLM

### ISSUE THREAD

**Issue by marcos-abreu** [abacusai/codellm-releases#1]
This repository doesn't have any documentation for CodeLLM. I'm a new subscriber to Abacus.AI and one of the tools it lists is CodeLLM and this repository is the only mention of CodeLLM I could find from Abacus, but the README file doesn't have any documentation.

Please add necessary documentation to README.

**Comment by aminya** [comment]
Thanks for reaching out. We appreciate your interest in CodeLLM. Stay tuned for the launch! We'll provide the necessary documentation on the website soon.

https://abacus.ai/
