### ISSUE TITLE
Error when interacting with an empty file in CodeLLM

### ISSUE THREAD

**Issue by rajeshkanaka** [abacusai/codellm-releases#5]
### **Description**
When I open an empty file in the CodeLLM-supported editor and attempt to interact with the chat (e.g., sending a simple "hi"), an error occurs. The error message indicates an invalid parameter `fileContents`. 

### **Steps to Reproduce**
1. Open the CodeLLM-supported code editor.
2. Create or open an empty file (no content in the file).
3. Type "hi" (or any input) in the CodeLLM chat interface.
4. Observe the error message.

### **Expected Behavior**
The interaction with the chat should process without throwing an error, even if the file is empty.

### **Actual Behavior**
An error message is displayed:
```
Error: Invalid parameter 'fileContents'. Received: '{"/path/to/empty/file.py": ""}'. File contents must be a dictionary with file names (str) as keys and file contents (str) as values.
```

### **Additional Context**
The issue seems to stem from the CodeLLM extension failing to handle files with empty content. The system attempts to pass an empty string for the file contents but fails validation. A screenshot is attached for further clarification.

![CleanShot 2024-12-22 at 01 21 14@2x](https://github.com/user-attachments/assets/54563a94-45f8-45d0-8154-eff12f649f4b)

**Comment by aminya** [comment]
Thanks for reporting this bug. I can confirm the issue.

**Comment by aminya** [comment]
This is now fixed in the latest version. 
https://github.com/abacusai/codellm-releases/releases/tag/1.95.3.24362
